version: "3.7"
services:
  react:
    stdin_open: true
    tty: true
    restart: always
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - node
      - mysql

  node:
    restart: always
    environment:
      - HOST=mysql
    build: ./back-end
    ports:
      - 3001:3001
    volumes:
      - ./:/code
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'delivery-app'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql
# Names our volume
volumes:
  mysql:
