version: "3.7"
services:
  react:
    stdin_open: true
    tty: true
    restart: always
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - node
      - mysql

  node:
    restart: always
    build: ./back-end
    ports:
      - 3001:3001
    volumes:
      - ./:/code
